# Generated by Django 4.2.23 on 2025-07-05 03:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
